"use client";
import { maskAddress } from "@/lib/mask-address";
import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar";
import { Button } from "./ui/button";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "./ui/tooltip";

interface userInfoProps{
    userWalletAddresss:string;
    userOwnedNFTs:number;
}

export default function UserInfo({userWalletAddresss,userOwnedNFTs}:userInfoProps){

    function handleWithdrawProceedings() {
        // TODO: Implement handle withdraw
    }

    return (
        <div className="flex flex-col md:flex-row items-center justify-between space-x-4  p-6">
                <div className="flex justify-center items-center gap-3">
                    <Avatar className="w-12 h-12">
                        <AvatarImage src="/avatar.png" />
                        <AvatarFallback>OM</AvatarFallback>
                    </Avatar>
                    <div className="flex items-start flex-col justify-center">
                        <p className="text-lg font-medium leading-none">
                            <span className="font-semibold text-accent-foreground">Wallet Address:</span> {maskAddress(userWalletAddresss, 7)}
                        </p>
                        <p className="text-lg text-muted-foreground">Owned Characters: {userOwnedNFTs}</p>
                    </div>
                </div>
                <div className="mt-4">
                    <TooltipProvider>
                        <Tooltip>
                            <TooltipTrigger asChild>
                                <Button size={"lg"} onClick={handleWithdrawProceedings}>
                                    Withdraw
                                </Button>
                            </TooltipTrigger>
                            <TooltipContent>
                                <p className="text-sm md:text-lg text-muted-foreground">
                                    Withdraw proceedings generated by sales of NFTs
                                </p>
                            </TooltipContent>
                        </Tooltip>
                    </TooltipProvider>
                </div>
            </div>
           
    )
}